namespace DroneDefender.Game.Signals {
	public enum InputContexts {
		UKNOWN,
		PAD_TOUCHED,
		PAD_UNTOUCHED,
		TRIGGER_CLICKED,
		MENU_BUTTON_CLICKED,
		GRIPPED,
		MOUSE_0_PRESSED,
		MOUSE_1_PRESSED,
		SECONDARY_FORWARD_PRESSED,
		SECONDARY_BACK_PRESSED,
		SECONDARY_LEFT_PRESSED,
		SECONDARY_RIGHT_PRESSED
	}
}
